version: "3"

services:
  nginxproxy:
    image: nginx:1.18.0
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  web:
    container_name: web
    build: .
    ports:
      - 5001:3000
    depends_on:
      - nginxproxy
    restart: always